# Generated by Django 5.2.4 on 2025-08-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='image',
            field=models.ImageField(default=1, upload_to='Uploads/pictures/'),
            preserve_default=False,
        ),
    ]
