# Generated by Django 5.2.4 on 2025-08-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_customers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
